"""initial schema

Revision ID: c181294d3737
Revises:
Create Date: 2026-09-22 00:37:45.452161

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c181294d3737"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("industry", sa.String(length=60), nullable=True),
        sa.Column("years_in_business", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("annual_revenue", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("has_physical_location", sa.Boolean(), nullable=True),
        sa.Column("is_us_based", sa.Boolean(), nullable=True),
        sa.Column("trucks_operated", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lenders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("contact_email", sa.String(length=200), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "loan_applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("term_months", sa.Integer(), nullable=True),
        sa.Column("transaction_type", sa.String(length=30), nullable=True),
        sa.Column("down_payment_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("soft_cost_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("corp_only", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount IS NULL OR amount > 0", name="ck_loan_applications_amount_positive"
        ),
        sa.CheckConstraint(
            "term_months IS NULL OR term_months > 0", name="ck_loan_applications_term_positive"
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id"),
    )
    op.create_index(
        op.f("ix_loan_applications_status"), "loan_applications", ["status"], unique=False
    )
    op.create_table(
        "policy_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lender_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_document", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lender_id"], ["lenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lender_id", "version_number", name="uq_policy_versions_lender_version"
        ),
    )
    op.create_index(
        op.f("ix_policy_versions_lender_id"), "policy_versions", ["lender_id"], unique=False
    )
    op.create_index(
        "uq_policy_versions_one_draft",
        "policy_versions",
        ["lender_id"],
        unique=True,
        postgresql_where=sa.text("status = 'draft'"),
    )
    op.create_index(
        "uq_policy_versions_one_published",
        "policy_versions",
        ["lender_id"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "business_credit_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("paynet_score", sa.Integer(), nullable=True),
        sa.Column("trade_lines_count", sa.Integer(), nullable=True),
        sa.Column("trade_history_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("largest_comparable_credit", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("comparable_contracts_count", sa.Integer(), nullable=True),
        sa.Column("clean_payment_history_months", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id"),
    )
    op.create_table(
        "equipment_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("model_year", sa.Integer(), nullable=True),
        sa.Column("condition", sa.String(length=10), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("hours", sa.Integer(), nullable=True),
        sa.Column("is_titled", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_equipment_items_application_id"),
        "equipment_items",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "guarantors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("ownership_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("fico_score", sa.Integer(), nullable=True),
        sa.Column("is_homeowner", sa.Boolean(), nullable=True),
        sa.Column("years_at_residence", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("is_us_citizen", sa.Boolean(), nullable=True),
        sa.Column("industry_experience_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("has_cdl", sa.Boolean(), nullable=True),
        sa.Column("cdl_class", sa.String(length=1), nullable=True),
        sa.Column("cdl_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("is_licensed_medical_professional", sa.Boolean(), nullable=True),
        sa.Column("years_licensed", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("revolving_credit_limit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("revolving_balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unsecured_debt", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("has_bankruptcy", sa.Boolean(), nullable=False),
        sa.Column("bankruptcy_discharge_date", sa.Date(), nullable=True),
        sa.Column("has_judgments", sa.Boolean(), nullable=False),
        sa.Column("has_foreclosures", sa.Boolean(), nullable=False),
        sa.Column("has_repossessions", sa.Boolean(), nullable=False),
        sa.Column("has_tax_liens", sa.Boolean(), nullable=False),
        sa.Column("has_recent_collections", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fico_score IS NULL OR fico_score BETWEEN 300 AND 850", name="ck_guarantors_fico_range"
        ),
        sa.CheckConstraint(
            "ownership_pct IS NULL OR ownership_pct BETWEEN 0 AND 100",
            name="ck_guarantors_ownership_range",
        ),
        sa.ForeignKeyConstraint(["application_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guarantors_application_id"), "guarantors", ["application_id"], unique=False
    )
    op.create_table(
        "programs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("applies_when", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rank >= 1", name="ck_programs_rank_positive"),
        sa.ForeignKeyConstraint(["policy_version_id"], ["policy_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_programs_policy_version_id"), "programs", ["policy_version_id"], unique=False
    )
    op.create_table(
        "underwriting_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=100), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("feature_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_underwriting_runs_application_id"),
        "underwriting_runs",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_underwriting_runs_status"), "underwriting_runs", ["status"], unique=False
    )
    op.create_table(
        "lender_match_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("lender_id", sa.UUID(), nullable=False),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("lender_name", sa.String(length=200), nullable=False),
        sa.Column("policy_version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("matched_program_name", sa.String(length=120), nullable=True),
        sa.Column("fit_score", sa.Integer(), nullable=False),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("near_miss_ratio", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("rejection_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("program_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("program_summaries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lender_id"],
            ["lenders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["underwriting_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lender_match_results_run_id"), "lender_match_results", ["run_id"], unique=False
    )
    op.create_table(
        "policy_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("field_key", sa.String(length=80), nullable=True),
        sa.Column("operator", sa.String(length=30), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("alternatives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applies_when", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message_template", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'simple' AND field_key IS NOT NULL AND operator IS NOT NULL) OR (kind = 'any_of' AND jsonb_array_length(alternatives) > 0)",
            name="ck_policy_rules_kind_shape",
        ),
        sa.CheckConstraint("kind IN ('simple', 'any_of')", name="ck_policy_rules_kind"),
        sa.CheckConstraint("severity IN ('hard', 'soft')", name="ck_policy_rules_severity"),
        sa.ForeignKeyConstraint(["policy_version_id"], ["policy_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["program_id"], ["programs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_rules_policy_version_id"),
        "policy_rules",
        ["policy_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_rules_program_id"), "policy_rules", ["program_id"], unique=False
    )
    op.create_table(
        "criterion_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_result_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("program_name", sa.String(length=120), nullable=True),
        sa.Column("program_rank", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("outcome", sa.String(length=10), nullable=False),
        sa.Column("field_key", sa.String(length=80), nullable=True),
        sa.Column("operator", sa.String(length=30), nullable=True),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("actual", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_result_id"], ["lender_match_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_criterion_results_match_result_id"),
        "criterion_results",
        ["match_result_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_criterion_results_match_result_id"), table_name="criterion_results")
    op.drop_table("criterion_results")
    op.drop_index(op.f("ix_policy_rules_program_id"), table_name="policy_rules")
    op.drop_index(op.f("ix_policy_rules_policy_version_id"), table_name="policy_rules")
    op.drop_table("policy_rules")
    op.drop_index(op.f("ix_lender_match_results_run_id"), table_name="lender_match_results")
    op.drop_table("lender_match_results")
    op.drop_index(op.f("ix_underwriting_runs_status"), table_name="underwriting_runs")
    op.drop_index(op.f("ix_underwriting_runs_application_id"), table_name="underwriting_runs")
    op.drop_table("underwriting_runs")
    op.drop_index(op.f("ix_programs_policy_version_id"), table_name="programs")
    op.drop_table("programs")
    op.drop_index(op.f("ix_guarantors_application_id"), table_name="guarantors")
    op.drop_table("guarantors")
    op.drop_index(op.f("ix_equipment_items_application_id"), table_name="equipment_items")
    op.drop_table("equipment_items")
    op.drop_table("business_credit_profiles")
    op.drop_index(
        "uq_policy_versions_one_published",
        table_name="policy_versions",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_index(
        "uq_policy_versions_one_draft",
        table_name="policy_versions",
        postgresql_where=sa.text("status = 'draft'"),
    )
    op.drop_index(op.f("ix_policy_versions_lender_id"), table_name="policy_versions")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_loan_applications_status"), table_name="loan_applications")
    op.drop_table("loan_applications")
    op.drop_table("lenders")
    op.drop_table("businesses")
    # ### end Alembic commands ###
