"""ingestion jobs

Revision ID: e2a87be9f906
Revises: c181294d3737
Create Date: 2026-09-22 01:47:05.324494

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2a87be9f906"
down_revision: str | Sequence[str] | None = "c181294d3737"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lender_id", sa.UUID(), nullable=True),
        sa.Column("new_lender_name", sa.String(length=200), nullable=True),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=100), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("extracted_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("uncertainties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extractor", sa.String(length=80), nullable=True),
        sa.Column("policy_version_id", sa.UUID(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lender_id"], ["lenders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["policy_version_id"], ["policy_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_lender_id"), "ingestion_jobs", ["lender_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_policy_version_id"),
        "ingestion_jobs",
        ["policy_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_policy_version_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_lender_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    # ### end Alembic commands ###
